on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      projectPath: "src/Alschy.QueueWorker.Azure.ServiceBus/Alschy.QueueWorker.Azure.ServiceBus.csproj"
      slnPath:  "src/Alschy.QueueWorker.Azure.ServiceBus/Alschy.QueueWorker.Azure.ServiceBus.sln"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with: 
          dotnet-version: 6.0.x
      - name: Set nuget.org
        run: dotnet nuget add source https://api.nuget.org/v3/index.json --name nuget.org
      - name: Restore
        run: dotnet restore $projectPath -v n
      - name: Build
        run: dotnet build $projectPath -c Release
