
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      projectPath: "src/Alschy.QueueWorker.Azure.ServiceBus/Alschy.QueueWorker.Azure.ServiceBus.csproj"
      output: "bin/"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with: 
          dotnet-version: 6.0.x
      - name: Restore
        run: dotnet restore $projectPath -v d
      - name: Pack
        run: dotnet pack $projectPath -c Release --no-restore -o $output
      - name: Push
        run: dotnet nuget push $output --api-key ${{ secrets.NUGET_API_KEY }}
